### ISSUE TITLE
How to create parameters for function?

### ISSUE THREAD

**Issue by cloudrex** [MichaReiser/llvm-node#79]
I'm having trouble defining function arguments, how can I create the formal parameter list and assign it to a function?

**Comment by MichaReiser** [comment]
The same as you would with the llvm when you’re not using the bindings

But you can find an example here
https://github.com/MichaReiser/speedy.js/blob/4b96e891e79515463aecc3ebdbab403ec08a03b8/packages/compiler/src/code-generation/value/function-factory.ts#L112

I thought I have tests for all IR instructions but this doesn’t seem to be
the case. Otherwise I could have pointed you to a test cast

**Comment by cloudrex** [comment]
Oh yes of course! I got confused for a second thought FunctionType only referred to its return value!

Thanks for your help.
